### PR TITLE
Feature/main layout

### PR DESCRIPTION
**Pull request by bmlancien**
The layout should now be responsive.

### CODE REVIEW

**Review by henhuy — APPROVED** [review]
Nice!

**Comment by henhuy** [comment]
Can you solve merge conflicts? Don't want to break css...

**Comment by bmlancien** [comment]
It was better for me to solve the conflicts in the editor since I compile the SCSS into CSS directly there. Can you check it again and merge if it works? Thanks

**Comment by henhuy** [comment]
Looks nice, except last tile (#6) where share button moves to the right. But maybe this is not a big problem?
Looking at tile 6 only - everything looks nice.
Rendering problems like in tile 4 are due to my "old-style-width-calculation" - will fix in another PR.
Shall I merge?

**Pull request merged**
